# Generated by Django 5.0.3 on 2024-08-15 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_executedoperation_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECSTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_arn', models.CharField(max_length=256)),
                ('revision_date', models.DateTimeField(auto_now_add=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.operation')),
            ],
        ),
    ]
