# Generated by Django 5.0.3 on 2024-08-19 18:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_ecstask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executedoperation',
            name='job_id',
            field=models.CharField(default=uuid.uuid4, max_length=128, null=True),
        ),
    ]
