site_name: WebMeV REST API
site_url: 'https://webmev.tm4.org'
site_description: Documentation for the WebMeV RESTful API

repo_url: https://github.com/web-mev/mev-backend

markdown_extensions:
 - toc:
    anchorlink: True
 - admonition
 - codehilite
 - mkautodoc

theme: readthedocs
extra_css: [style.css]

nav:
 - Home: 'index.md'
 - Architecture: 'general_architecture.md'
 - Installation and Setup: 
   - Install: 'install.md'
   - Configuration: 'setup_configuration.md'
   - Management commands: 'management_commands.md'
 - API: 
   - Intro and core concepts: 'api.md'
   - Data Structures:
      - Resources: 
         - General info: 'resources.md'
         - Resource types: 'resource_types.md'
         - Resource metadata: 'resource_metadata.md'
         - Operation-associated resources: 'operation_resources.md'
      - Attributes: 'attributes.md'
      - Observations and Features: 'elements.md'
      - ObservationSet and FeatureSets: 'observation_and_feature_sets.md'
      - Workspaces: 'workspaces.md'
      - Workspace metadata: 'metadata.md'
 - Authentication: 'auth.md'
 - Operation concepts: 'operations.md'
 - Creating new analyses/operations: 'creating_analyses.md'
 - Workflow and analysis concepts: 'example_workflow.md'
 - Creating and managing public data: 'public_data.md'

